// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteFortesTecnologia.Data;

#nullable disable

namespace TesteFortesTecnologia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430201447_AlterMatriculaCursoManyToMany")]
    partial class AlterMatriculaCursoManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("TesteFortesTecnologia.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatriculaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.MatriculaCurso", b =>
                {
                    b.Property<int>("MatriculaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatriculaId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("MatriculaCurso");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Matricula", b =>
                {
                    b.HasOne("TesteFortesTecnologia.Models.Aluno", "Aluno")
                        .WithOne("Matricula")
                        .HasForeignKey("TesteFortesTecnologia.Models.Matricula", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.MatriculaCurso", b =>
                {
                    b.HasOne("TesteFortesTecnologia.Models.Curso", "Curso")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteFortesTecnologia.Models.Matricula", "Matricula")
                        .WithMany("MatriculaCursos")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Aluno", b =>
                {
                    b.Navigation("Matricula")
                        .IsRequired();
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Curso", b =>
                {
                    b.Navigation("MatriculaCursos");
                });

            modelBuilder.Entity("TesteFortesTecnologia.Models.Matricula", b =>
                {
                    b.Navigation("MatriculaCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
